load("//javatests/com/google/gerrit/acceptance:tests.bzl", "acceptance_tests")

acceptance_tests(
    srcs = glob(
        ["javatests/com/google/gerrit/plugins/startblock/**/*.java"]),
    group = "startblock",
    deps = [
        "//plugins/startblock:startblock__plugin",
    ],
)


